# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: run AZ CLI on Ubuntu
  jobs:
  - job: PowerShellExec
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@1
      inputs:
          azureSubscription: 'sqldevopsdemosub-test'
          scriptLocation: 'inlineScript'
          inlineScript: 'az group list'

- stage: run PowerShell on Windows
  jobs:
  - job: PowerShellExec
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureCLI@1
      inputs:
          azureSubscription: 'sqldevopsdemosub-test'
          scriptLocation: 'inlineScript'
          inlineScript: 'Get-AzResourceGroup'
